name: medical_devices_app

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_localization: ^0.1.13
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  skeletons: ^0.0.3
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icons/logoIcon.png'
  remove_alpha_ios: true
  background_color: '#FFFFFF'

flutter_native_splash:
  android: true
  ios: true
  color: '#FFFFFF'
  image: assets/images/logo3.png
  

  fullscreen: true

  android_12:
    image: assets/images/logo3.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"


flutter:

 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    # - family: Poppins
    #   fonts:
    #     - asset: assets/fonts/Poppins-Light.ttf
    #       weight: 300
    #     - asset: assets/fonts/Poppins-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/Poppins-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/Poppins-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/Poppins-Bold.ttf
    #       weight: 700

    - family: AvenirArabic
      fonts:
        - asset: assets/fonts/avenir-arabic-black.otf
          weight: 700
        - asset: assets/fonts/avenir-arabic-medium.otf
          weight: 400
  

